// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type File struct {
	ID         pgtype.UUID        `json:"id"`
	Path       string             `json:"path"`
	FileName   string             `json:"file_name"`
	Type       string             `json:"type"`
	Size       int64              `json:"size"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	Sha256     pgtype.Text        `json:"sha256"`
	FolderID   pgtype.UUID        `json:"folder_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type FilesCategory struct {
	FileID     pgtype.UUID `json:"file_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type Folder struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Path           string             `json:"path"`
	ParentFolderID pgtype.UUID        `json:"parent_folder_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type FoldersCategory struct {
	FolderID   pgtype.UUID `json:"folder_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type Scan struct {
	ID        pgtype.UUID        `json:"id"`
	Status    string             `json:"status"`
	Found     pgtype.Int4        `json:"found"`
	Processed pgtype.Int4        `json:"processed"`
	Progress  pgtype.Int4        `json:"progress"`
	Error     pgtype.Text        `json:"error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
