// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFileCategory(ctx context.Context, arg AddFileCategoryParams) error
	AddFolderCategory(ctx context.Context, arg AddFolderCategoryParams) error
	BulkAddFileCategories(ctx context.Context, arg BulkAddFileCategoriesParams) error
	BulkAddFolderCategories(ctx context.Context, arg BulkAddFolderCategoriesParams) error
	BulkRemoveFileCategories(ctx context.Context, fileIds []pgtype.UUID) error
	BulkRemoveFolderCategories(ctx context.Context, folderIds []pgtype.UUID) error
	CountCategories(ctx context.Context) (int64, error)
	CountFiles(ctx context.Context) (int64, error)
	CountFilesByType(ctx context.Context, type_ string) (int64, error)
	CountFolderFiles(ctx context.Context, folderID pgtype.UUID) (int64, error)
	CountFolders(ctx context.Context) (int64, error)
	CountRootFiles(ctx context.Context) (int64, error)
	CountRootFolders(ctx context.Context) (int64, error)
	CountScans(ctx context.Context) (int64, error)
	CountSearchCategories(ctx context.Context, search string) (int64, error)
	CountSearchFolders(ctx context.Context, search string) (int64, error)
	CountSearchRootFolders(ctx context.Context, search string) (int64, error)
	CountSubfolders(ctx context.Context, parentFolderID pgtype.UUID) (int64, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateFolderWithParent(ctx context.Context, arg CreateFolderWithParentParams) (Folder, error)
	CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error)
	DeleteCategory(ctx context.Context, id pgtype.UUID) error
	DeleteFile(ctx context.Context, id pgtype.UUID) error
	DeleteFolder(ctx context.Context, id pgtype.UUID) error
	DeleteScan(ctx context.Context, id pgtype.UUID) error
	GetCategoriesBatch(ctx context.Context, fileIds []pgtype.UUID) ([]GetCategoriesBatchRow, error)
	GetCategory(ctx context.Context, id pgtype.UUID) (Category, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetFile(ctx context.Context, id pgtype.UUID) (File, error)
	GetFileByPath(ctx context.Context, path string) (File, error)
	GetFileCategories(ctx context.Context, fileID pgtype.UUID) ([]Category, error)
	GetFilesByCategory(ctx context.Context, arg GetFilesByCategoryParams) ([]File, error)
	GetFolder(ctx context.Context, id pgtype.UUID) (Folder, error)
	GetFolderByPath(ctx context.Context, path string) (Folder, error)
	GetFolderCategories(ctx context.Context, folderID pgtype.UUID) ([]Category, error)
	GetFolderCategoriesBatch(ctx context.Context, folderIds []pgtype.UUID) ([]GetFolderCategoriesBatchRow, error)
	GetFolderFiles(ctx context.Context, folderID pgtype.UUID) ([]File, error)
	GetFolderFilesPaginated(ctx context.Context, arg GetFolderFilesPaginatedParams) ([]File, error)
	GetScan(ctx context.Context, id pgtype.UUID) (Scan, error)
	ListAllFiles(ctx context.Context) ([]File, error)
	ListAllFilesPaginated(ctx context.Context, arg ListAllFilesPaginatedParams) ([]File, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoriesPaginated(ctx context.Context, arg ListCategoriesPaginatedParams) ([]Category, error)
	ListFiles(ctx context.Context, arg ListFilesParams) ([]File, error)
	ListFolders(ctx context.Context) ([]Folder, error)
	ListFoldersPaginated(ctx context.Context, arg ListFoldersPaginatedParams) ([]Folder, error)
	ListRootFiles(ctx context.Context) ([]File, error)
	ListRootFilesPaginated(ctx context.Context, arg ListRootFilesPaginatedParams) ([]File, error)
	ListRootFolders(ctx context.Context) ([]Folder, error)
	ListRootFoldersPaginated(ctx context.Context, arg ListRootFoldersPaginatedParams) ([]Folder, error)
	ListScans(ctx context.Context, arg ListScansParams) ([]Scan, error)
	ListSubfolders(ctx context.Context, parentFolderID pgtype.UUID) ([]Folder, error)
	ListSubfoldersPaginated(ctx context.Context, arg ListSubfoldersPaginatedParams) ([]Folder, error)
	RemoveAllFileCategories(ctx context.Context, fileID pgtype.UUID) error
	RemoveFileCategory(ctx context.Context, arg RemoveFileCategoryParams) error
	RemoveFolderCategory(ctx context.Context, arg RemoveFolderCategoryParams) error
	RestoreCategory(ctx context.Context, id pgtype.UUID) error
	SearchCategoriesPaginated(ctx context.Context, arg SearchCategoriesPaginatedParams) ([]Category, error)
	SearchFiles(ctx context.Context, arg SearchFilesParams) ([]SearchFilesRow, error)
	SearchFoldersPaginated(ctx context.Context, arg SearchFoldersPaginatedParams) ([]Folder, error)
	SearchRootFoldersPaginated(ctx context.Context, arg SearchRootFoldersPaginatedParams) ([]Folder, error)
	SetFolderCategories(ctx context.Context, folderID pgtype.UUID) error
	SoftDeleteCategory(ctx context.Context, id pgtype.UUID) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error)
	UpdateFileFolderID(ctx context.Context, arg UpdateFileFolderIDParams) error
	UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error)
	UpdateFolderParent(ctx context.Context, arg UpdateFolderParentParams) (Folder, error)
	UpdateScan(ctx context.Context, arg UpdateScanParams) (Scan, error)
	UpsertFile(ctx context.Context, arg UpsertFileParams) (File, error)
}

var _ Querier = (*Queries)(nil)
