// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countScans = `-- name: CountScans :one
SELECT COUNT(*) FROM scans
`

func (q *Queries) CountScans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countScans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScan = `-- name: CreateScan :one
INSERT INTO scans (status, found, processed, progress)
VALUES ($1, $2, $3, $4)
RETURNING id, status, found, processed, progress, error, created_at, updated_at
`

type CreateScanParams struct {
	Status    string      `json:"status"`
	Found     pgtype.Int4 `json:"found"`
	Processed pgtype.Int4 `json:"processed"`
	Progress  pgtype.Int4 `json:"progress"`
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, createScan,
		arg.Status,
		arg.Found,
		arg.Processed,
		arg.Progress,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Found,
		&i.Processed,
		&i.Progress,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScan = `-- name: DeleteScan :exec
DELETE FROM scans WHERE id = $1
`

func (q *Queries) DeleteScan(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteScan, id)
	return err
}

const getScan = `-- name: GetScan :one
SELECT id, status, found, processed, progress, error, created_at, updated_at FROM scans WHERE id = $1 LIMIT 1
`

func (q *Queries) GetScan(ctx context.Context, id pgtype.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, getScan, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Found,
		&i.Processed,
		&i.Progress,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScans = `-- name: ListScans :many
SELECT id, status, found, processed, progress, error, created_at, updated_at FROM scans
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListScansParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListScans(ctx context.Context, arg ListScansParams) ([]Scan, error) {
	rows, err := q.db.Query(ctx, listScans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scan{}
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Found,
			&i.Processed,
			&i.Progress,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScan = `-- name: UpdateScan :one
UPDATE scans
SET status = $2, found = $3, processed = $4, progress = $5, error = $6, updated_at = now()
WHERE id = $1
RETURNING id, status, found, processed, progress, error, created_at, updated_at
`

type UpdateScanParams struct {
	ID        pgtype.UUID `json:"id"`
	Status    string      `json:"status"`
	Found     pgtype.Int4 `json:"found"`
	Processed pgtype.Int4 `json:"processed"`
	Progress  pgtype.Int4 `json:"progress"`
	Error     pgtype.Text `json:"error"`
}

func (q *Queries) UpdateScan(ctx context.Context, arg UpdateScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, updateScan,
		arg.ID,
		arg.Status,
		arg.Found,
		arg.Processed,
		arg.Progress,
		arg.Error,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Found,
		&i.Processed,
		&i.Progress,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
